### ISSUE TITLE
`cloudstack.network_type` is not automatically configured in the API

### ISSUE THREAD

**Issue by awheeler** [Scalr/scalr#47]
I need to create farms completely from scratch via API on CloudStack, and this line:
https://github.com/Scalr/scalr/blob/master/app/src/api/class.ScalrAPI_2_3_0.php#L283
is preventing it, but I don't see any reason CloudStack wouldn't work just fine.

**Comment by awheeler** [comment]
Any timeline on this?

**Comment by krallin** [comment]
@DicsyDel ?

**Comment by DicsyDel** [comment]
That was fixed in 5.3. Feel free to re-open this ticket if you'll have any issues with this. "cloudstack.network_type" should not be configured during farm configuration. It will be automatically configured after launch of first instance of this FarmRole.

Regards,
Igor
