### ISSUE TITLE
Issue booting CentOS7 image

### ISSUE THREAD

**Issue by wingZero21** [Scalr/scalr#54]
Hi,

Just wanted to confirm if we are able to boot CentOS7 images in scalr currently.

There was an issue initially which I have resolved by amending one of the py scripts which is checking for the lease file to create the role/image. 

However when attempting to boot the image its currently sticking in a pending state. 

Details on scalarizr issue now resolved:
https://github.com/Scalr/scalarizr/pull/11
https://github.com/Scalr/scalarizr/issues/5

**Comment by maratkomarov** [comment]
We've just released Scalarizr 3.3.3 with a fix for leases pattern. Please try it again

**Comment by wingZero21** [comment]
Hi,

I have tried this again with 3.3.3 however when booting the image its still just getting stuck in the pending state.

**Comment by maratkomarov** [comment]
scalarizr_debug.log will be helpful

**Comment by wingZero21** [comment]
Hi,

I have attached the log as requested.
[scalarizr_debug.log | uploaded via ZenHub](https://files.zenhub.io/54ca49f2ea33564f0cc0a385)

**Comment by maratkomarov** [comment]
You have a 3.3.2 bundled on this server, and it can't start and update to 3.3.3 because of discussed issue. Please create new role with a 3.3.3

Regads,
Marat

**Comment by wingZero21** [comment]
Hi,

I have created a new role with 3.3.3 however the same issue still seems to occur.

This is the agent that is installed on the image currently.

```
[root@centos7-prod-dc1 log]# rpm -qa | grep scalar
scalarizr-cloudstack-3.3.3-1.x86_64
scalarizr-3.3.3-1.x86_64
```

**Comment by maratkomarov** [comment]
The log you've provided seems from instance you've imported. Please attach log from server hanged in Pending

**Comment by wingZero21** [comment]
Hi,

I have added latest onto the farm the and the image has now booted.

Cheers!
