### ISSUE TITLE
Query on Storage API adding a second disk to role/server

### ISSUE THREAD

**Issue by wingZero21** [Scalr/scalr#55]
Hi,

Do you know if its going to be possible to add a second disk to the role/server within the API.

Currently this is available to perform within the gui. I cant find anything on the docs to confirm this currently, do you know if this is a feature that is being looked at?

**Comment by krallin** [comment]
Do you mean adding a new storage entry in the Storage Tab? If that is correct, the yes, ultimately, you will be able to do so.
