### ISSUE TITLE
Query on chef-zero

### ISSUE THREAD

**Issue by wingZero21** [Scalr/scalr#56]
Hi,

Do you know if there are any plans to support chef-zero as an option within scalr?

Based on this article it looks like it will eventually succeed solo.

https://www.chef.io/blog/2014/06/24/from-solo-to-zero-migrating-to-chef-client-local-mode/

**Comment by krallin** [comment]
Hey there,

This isn't currently planned. 

Naturally, we'll look into it if Chef-Solo ends up deprecated and we see substantial customer demand for it!

Cheers,
