### ISSUE TITLE
After rebooting the volumes don't remount

### ISSUE THREAD

**Issue by awheeler** [Scalr/scalr#57]
This is similar to #46, but doesn't appear to be related to reuse setting.
Running scalr 5.1, and scalarizr 3.2.4, cloudstack.
The filesystems mount correctly on creation, but not on reboot.
No entries are created in /etc/fstab.

**Comment by maratkomarov** [comment]
Issue was fixed in 3.3.15 / 3.2.5

**Comment by awheeler** [comment]
Excellent!  Thank you!
