### ISSUE TITLE
No module named rackspacenguk

### ISSUE THREAD

**Issue by dandart** [Scalr/scalr#58]
Getting this error when I start scalarizr.

Using scalarizr 3.1.10 (3.1.7 didn't agree with it either).
This causes scalr not to be able to run scripts on our system.

I have scalarizr and scalarizr-openstack installed in ubuntu.

Please help us solve this

Cheers

**Comment by DicsyDel** [comment]
What version of scalr you're using?

**Comment by dandart** [comment]
On v. 4.5 as upgrades haven't been made easy for our setup

**Comment by DicsyDel** [comment]
Issue was fixed in Scalr >= 5.0 . You'll need to upgrade scalr to fix this issue.

Regards,
Igor
