### ISSUE TITLE
Any chance for vCloud integration?

### ISSUE THREAD

**Issue by asciifaceman** [Scalr/scalr#65]
Enhancement request I guess, wondering if VMWare vCloud is on the roadmap.

**Comment by SebastianStadil** [comment]
Hey @asciifaceman, welcome to the community!

We haven't seen any demand for vCloud, so it isn't. Sorry we can't accommodate!

**Comment by asciifaceman** [comment]
Thank you for your very fast response.

I can 100% understand why there is no demand for it, it is atrocious. The only reason I am even working with it is because people in suits make decisions ;)

**Comment by SebastianStadil** [comment]
Yeah, one quick look at the API and we ran away. I totally get that you'd want to use the Scalr API instead of the vCloud one.
