### ISSUE TITLE
Scalr API does not honor API keys when auth_mode is ldap

### ISSUE THREAD

**Issue by awheeler** [Scalr/scalr#66]
Running latest Scalr community: 5.8.29
I need users to be able to login via ldap, but I need automated processes to login via API keys.
I don't see any way to set this up, but it looks like [class.ScalrAPICore.php](https://github.com/Scalr/scalr/blob/master/app/src/api/class.ScalrAPICore.php#L384) already supports passing an `AuthType` argument in the API call set to `ldap` to auth via ldap,
 so I'm not sure why [AuthenticateRESTv3](https://github.com/Scalr/scalr/blob/master/app/src/api/class.ScalrAPICore.php#L196) is also checking `scalr.auth_mode` for ldap.

**Comment by recipe** [comment]
AuthenticateRESTv3 does vital part of the authorisation - fetches LDAP groups for that requested user to Scalr because it affects ACL.

**Comment by awheeler** [comment]
Strange, it's not working for me at all -- all attempts to auth result in `Incorrect login or password (1) ` from: https://github.com/Scalr/scalr/blob/master/app/src/api/class.ScalrAPICore.php#L207

**Comment by awheeler** [comment]
Looks like it's a misconfig on my end.
