### ISSUE TITLE
Disable API Termination flag action missing

### ISSUE THREAD

**Issue by sacredwebsite** [Scalr/scalr#67]
I have a server which I enabled the "Disable API Termination flag" action on.
After immediately there is no option to enable or cancel the action.

This server has since been terminated in aws console.

Is there a way to purge this server now? the option to disable the action does not exist.
Any advice on where this action can be reverted is appreciated.

Best regards.

**Comment by DicsyDel** [comment]
Hi @sacredwebsite,

This is known issue in Scalr CE, and it was already fixed in the Enterprise Edition. We're preparing a new release for Comunity Edition (should be out within the next couple weeks) where the issue will be fixed.

As workaround, you can remove entry from scalr.server_properties table. Serch by server_id and name = 'ec2.is_locked'

Regards,
Igor

**Comment by sacredwebsite** [comment]
Thank you for your time @DicsyDel, I look forward to the upcoming release.

**Comment by sacredwebsite** [comment]
Was this feature completely removed or fixed? After applying the latest CE release the option to add the Disable API Termination flag is missing from the server action menu. Was it decided to keep this only as an API function?

**Comment by recipe** [comment]
It should appear in the server action menu (for AWS).

**Comment by recipe** [comment]
Which the status of the Scalr Server is in the grid?

**Comment by sacredwebsite** [comment]
I apologize, I assumed this function is also possible for GCE, is this AWS API specific call or a Scalr one?

**Comment by recipe** [comment]
It is AWS specific `DisableAPITermination` attribute for the [ModifyInstanceAttribute API call](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html)

**Comment by sacredwebsite** [comment]
thanks @recipe for helping me understand.
