### ISSUE TITLE
Email field validations do not consider new TLD

### ISSUE THREAD

**Issue by sacredwebsite** [Scalr/scalr#68]
Hi,
Thank you for a masterful software.
I am having an issue where Scalr will not allow me to use my domain address in any of the email fields.
I have a FQDN with a TLD of ".website", unfortunately, scalr thinks this is not a real email address and thus does not allow me to use this (inbox@example.website). This may be an issue that will be of greater consideration as more new TLDs are released and used in the market. right now some other ones are allow I noticed, such as ".me", is it possible to remove this validation / restriction throughout any email field?

**Comment by DicsyDel** [comment]
@Invar  Please take a look.

**Comment by DicsyDel** [comment]
Fixed in 5.10.21
