### ISSUE TITLE
Azure error. The api-version '2015-05-01-preview' is invalid

### ISSUE THREAD

**Issue by hassanbabaie** [Scalr/scalr#71]
This may be user error but when trying to create an image from Azure running in ARM mode I get the error below: (Main Drop Down - Images - Create Image from non-Scalr Server)

Azure error. The api-version '2015-05-01-preview' is invalid.

It then lists a number of valid API's just not "2015-05-01-preview"

I'm running:

5.10.21 (Community Edition)
REVISION e67c67d (Tue, 5 Jan 2016 17:21:43 +0300)

Not sure if anyone else is seeing this and if so if it's just something that will be resolved on the next Community Edition update.

Thanks

Hass

**Comment by recipe** [comment]
Unfortunately this feature is not supported yet. Azure cloud is considered to be hidden from the feature "Create Image from non-Scalr Server".

**Comment by DicsyDel** [comment]
A bit more details: Azure ARM (new compute API) doesn't have APIs to work with images. There is no way to create or manage custom images, so Azure support right now is limited to pre-defined marketplace images of Ubuntu, CentOS and Windows.

Regards,
Igor

**Comment by hassanbabaie** [comment]
Thanks Vitaliy, given it's not hidden it might be worth noting that on the page. Just a thought.

Igor, thanks for the confirmation. Now one last ask as it's not mentioned anywhere that I could see, how to I get those images registered in Scalr?

Thanks!

**Comment by DicsyDel** [comment]
By syncing shared roles: https://scalr-wiki.atlassian.net/wiki/display/docs/Packages+-+Sync+Shared+Roles

Regards,
Igor

**Comment by hassanbabaie** [comment]
perfect, thanks Igor, I'll try this out later today

**Comment by hassanbabaie** [comment]
I'm waiting on the request to be approved and will then perform the test

**Comment by hassanbabaie** [comment]
Syncing has now resolved my problem, thank you both for the quick response
