### ISSUE TITLE
Can't use scalarizr on SL

### ISSUE THREAD

**Issue by jseaidou** [Scalr/scalr#72]
I tried running scalarizr on SL6. I managed to modify the install_scalarizr.sh script to be able to recognize it.
Now when I try and import a server into scalar to create a image from it, I can not get past the Role Creation Progress since the Operating System dropdown is empty.

**Comment by maratkomarov** [comment]
Scalr don't know about Scientific Linux. It's necessary to add it in Scalr scope into Operation Systems

![screen shot 2016-03-22 at 12 17 01 pm](https://cloud.githubusercontent.com/assets/1004449/13961743/e14a4de2-f02b-11e5-9ce1-4692a260fa72.png)

After that, you'll see it in OS dropdown.

As for install_scalarizr.sh we've issued internal ticket to add SL support.

Regards,
Marat

**Comment by jseaidou** [comment]
@maratkomarov can you tell me how you got to this page? I can't seem to find it in the Scalr UI

**Comment by mlochead** [comment]
@jseaidou you have to be logged on as a Scalr global admin, and it's an available option in the top menu "operating systems", when you are the "Scalr scope" which is what you should see when you login with an admin user.

**Comment by jseaidou** [comment]
Got it! thanks. That seems to have resolved it for me
