### ISSUE TITLE
Email comes malformed

### ISSUE THREAD

**Issue by teamfighter** [Scalr/scalr#73]
When I am configuring Scalr to send emails through relay, all letters comes in Base64 encoding, i.e. in client I have the following as a message body:

X-Mailer: SimpleMailer-0.2 PHP/5.6.17

Content-type: text/plain; charset=UTF-8

Date: Tue, 22 Mar 2016 14:31:50 +0000

Content-Transfer-Encoding: QUOTED-PRINTABLE

Message-ID: 7bf1ec928274530b5614a88c9c56c527.127.0.0.1
Return-Path: XXX@XXX
X-OriginalArrivalTime: 22 Mar 2016 14:31:50.0112 (UTC) FILETIME=[9237A600:01D18447]

CiwKCldlIHJlY2VpdmVkIGEgcmVxdWVzdCB0byByZXNldCB5b3VyIFNjYWxyIHBhc3N3b3JkLgoK
SWYgeWSWYgeW91IGRpZCBub3QgcmVxdWVzdCB0aGlzIGNoYSWYgeW91IGRpZCBub3QgcmVxdWVzdCB0aGlzIGNoYSWYgeW91IGRpZCBub3QgcmVxdWVzdCB0aGlzIGNoYh=
c2g9ZGNlMzk5YTA3NAoKVGhhbmsgeW91LApUaGUgU2NhbHIgVGVhbQ==

I repeat, I have this in email BODY.

Full message looks like this:

Delivered-To: eldar@xxxx.xxxx
Received: by 10.28.172.7 with SMTP id v7csp1857619wme;
        Tue, 22 Mar 2016 07:31:54 -0700 (PDT)
X-Received: by 10.112.130.41 with SMTP id ob9mr12951626lbb.81.1458657114805;
        Tue, 22 Mar 2016 07:31:54 -0700 (PDT)
Return-Path: <scalr-app@xxxxx.xxxx>
Received: from xxxx.xxxx ([0.0.0.1])
        by mx.google.com with ESMTP id e136si16088116lfg.155.2016.03.22.07.31.54
        for <eldar@xxxx.xxxx>;
        Tue, 22 Mar 2016 07:31:54 -0700 (PDT)
Received-SPF: neutral (google.com: 0.0.0.1 is neither permitted nor denied by best guess record for domain of scalr-app@xxxx.xxxx) client-ip=0.0.0.1;
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 0.0.0.1 is neither permitted nor denied by best guess record for domain of scalr-app@xxxxx.xxxx) smtp.mailfrom=scalr-app@xxxxx.xxxx
Date: Tue, 22 Mar 2016 07:31:54 -0700 (PDT)
Message-Id: <56f1575a.8ece190a.fc4e.7806SMTPIN_ADDED_MISSING@mx.google.com>
Received: from xxxxx.xxxx ([192.168.3.63]) by xxxxx.xxxx with Microsoft SMTPSVC(7.5.7601.17514);
	 Tue, 22 Mar 2016 17:31:49 +0300
Received: by xxxxx.xxxx (sSMTP sendmail emulation); Tue, 22 Mar 2016 14:31:50 +0000
From: scalr-app@xxxx.xxxx
To: eldar@xxxx.xxxx
Subject: =?UTF-8?B?W1NjYWxyXSBSZXNldCBZb3VyIFBhc3N3b3Jk?=
X-PHP-Originating-Script: 0:SimpleMailer.php
MIME-Version: 1.0
X-Mailer: SimpleMailer-0.2 PHP/5.6.17

Content-type: text/plain; charset=UTF-8

Date: Tue, 22 Mar 2016 14:31:50 +0000

Content-Transfer-Encoding: BASE64

Message-ID: 7bf1ec928274530b5614a88c9c56c527.127.0.0.1
Return-Path: XXX@XXX
X-OriginalArrivalTime: 22 Mar 2016 14:31:50.0112 (UTC) FILETIME=[9237A600:01D18447]

CiwKCldlIHJlY2VpdmVkIGEgcmVxdWVzdCB0byByZXNldCB5b3VyIFNjYWxyIHBhc3N3b3JkLgoK
SWYgeWSWYgeW91IGRpZCBub3QgcmVxdWVzdCB0aGlzIGNoYSWYgeW91IGRpZCBub3QgcmVxdWVzdCB0aGlzIGNoYSWYgeW91IGRpZCBub3QgcmVxdWVzdCB0aGlzIGNoYh=
c2g9ZGNlMzk5YTA3NAoKVGhhbmsgeW91LApUaGUgU2NhbHIgVGVhbQ==

Looks like SimpleMailer.php misconfiguration.

**Comment by recipe** [comment]
Given that https://github.com/Scalr/scalr/blob/master/app/src/Scalr/SimpleMailer.php#L28 it should send `Content-Transfer-Encoding` header as `BASE64`. There is no place in Scalr where it is overridden.

**Comment by teamfighter** [comment]
I have tried to change ENCODING_BASE64 variable from BASE64 to QUOTED-PRINTABLE.
All, that I got is just that:
Content-Transfer-Encoding: QUOTED-PRINTABLE instead of Content-Transfer-Encoding: BASE64 in body.
So this trick didnt worked for me.

**Comment by recipe** [comment]
I am closing this tread as we cannot reproduce this and haven't heard about similar issues from our community.

**Comment by ccheline** [comment]
I had this same issue, but found that the problem was in my scalr.email.delimiter option.

Since I am running scalr on UNIX, I had to change this to 'lf'.
The default is CRLF, which caused the header to be malformed and ended up in a difficult to read email.
