### ISSUE TITLE
rotated image

### ISSUE THREAD

**Issue by TimYi** [Scalr/scalr#75]
After resize, a rotated image won't rotate. It seems jpeg image has a TAG_ORIENTATION attribute, and scalr does not set it correctly.

**Comment by recipe** [comment]
@TimYi  What is the image you are talking about?

**Comment by TimYi** [comment]
something like this:
[A rotate image. It's rotate property is set to some degree.](http://cn.bing.com/images/search?q=image+rotate+property&view=detailv2&&id=6477920F525F90430EDCB9224DE7FA9724416CD3&selectedIndex=0&ccid=hb5joiMc&simid=608028423716864208&thid=OIP.M85be63a2231c8cf24fea561e181fddb9o0)

**Comment by TimYi** [comment]
@recipe the image is not rendered rotated. It has an rotate property, and the property is set to some value. After scalr resize the image, it's rotate property lost.

**Comment by recipe** [comment]
@TimYi Could you specify the steps to reproduce this issue in your version of Scalr. And link to screenshot to prove it does not work as expected. Which image in Scalr UI shows ugly in which circumstances?
