### ISSUE TITLE
Unable to login (xPostError /guest - Cannot read property 'trim' of undefined)

### ISSUE THREAD

**Issue by seriousjelly** [Scalr/scalr#83]
I last used my instance a week ago with no issues logging in at all. Yesterday I went to login and it hangs at the login screen. 

After inspecting the page I notice that an error is being sent to the /guest/xPostError url, the contents of which are:

```
message:t4 Cannot read property 'trim' of undefined
stack: TypeError: Cannot read property 'trim' of undefined
    at cacheLink (http://sub.mydomain/ui2/js/ui-1454677027.js:1694:34)
    at Object.success [as successF] (http://sub.mydomain/ui2/js/ui-1454677027.js:1829:189)
    at Object.callback (http://sub.mydomain/ui2/js/utils-1454677027.js:293:38)
    at Object.callback (http://sub.mydomain/ui2/js/extjs-5.0/ext-all-debug-1.js:7959:32)
    at constructor.onComplete (http://sub.mydomain/ui2/js/extjs-5.0/ext-all-debug-1.js:22759:13)
    at constructor.onStateChange (http://sub.mydomain/ui2/js/extjs-5.0/ext-all-debug-1.js:22688:16)
    at XMLHttpRequest.<anonymous> (http://sub.mydomain/ui2/js/extjs-5.0/ext-all-debug-1.js:6327:35)
type: undefined
name: TypeError
plugins:Widevine Content Decryption Module, Shockwave Flash, Chrome PDF Viewer, Native Client, Chrome PDF Viewer
url:http://sub.mydomain.com/#/dashboard
X-Requested-Token:XXXXXXXXXXXXXXXXXXXXXXXXXXX
```

The issue seems to be with this line `var cacheOriginal = cache.trim();` of the ui-1454677027.js file. 

Any ideas?

**Comment by seriousjelly** [comment]
@Invar A little more information for you, it would appear that a cacheId is not being found with in the request header: 

ui-1454677027.js Line: 1829
```                var c = 'Scalr.' + data.moduleName.replace('/ui2/js/', '').replace(/-[0-9]+.js/, '').replace(/\//g, '.'), cacheId = response.getResponseHeader('X-Scalr-Cache-Id'), cache = cacheLink(link, cacheId);
```

`response.getResponseHeader('X-Scalr-Cache-Id')` returns `undefined`

**Comment by seriousjelly** [comment]
Further comments:

Affects version 5.11.22 - Currently attempting a downgrade

A fresh install on a fresh Ubuntu 14.04 server results in the same issues as above.

**Comment by recipe** [comment]
@seriousjelly Please check that all response headers that are sent by Scalr reach your local machine. BTW Scalr does not support downgrade of existing and already deployed architecture.

**Comment by seriousjelly** [comment]
@recipe As mentioned above, it appears that the `X-Scalr-Cache-Id` header is missing from the request.

**Comment by seriousjelly** [comment]
@recipe By downgrade, I mean rebuilding the server and installing the lower version. Not overwriting the existing version.

**Comment by seriousjelly** [comment]
Turns out that this was related to an internal network issue.
