### ISSUE TITLE
AWS VM's stuck after Cloud-init

### ISSUE THREAD

**Issue by angarg12** [Scalr/scalr#87]
I have a local Scalr deployment and I was following the [3 Tier Web App](https://scalr-wiki.atlassian.net/wiki/display/docs/3+Tier+Web+Application+-+Deployment) tutorial.

All steps work fine, but when I try to deploy the farm in AWS, all the machines get stuck after Cloud-init. 

Here is the last line of the log

`Cloud-init v. 0.7.5 finished at Mon, 27 Mar 2017 13:06:49 +0000. Datasource DataSourceEc2.  Up 67.80 seconds`

Then the machines stay like that indefinitely.

**Comment by recipe** [comment]
Hi @angarg12 please ask this question in [Scalr Discuss](https://groups.google.com/forum/#!forum/scalr-discuss) Google group
