### ISSUE TITLE
documentation discrepancy

### ISSUE THREAD

**Issue by davemeekin** [Scalr/scalr#90]
The scalr api v2 documentation suggests 'status' should be returned when querying Farms https://api-explorer.scalr.com/user/farms/get.html

Running against the open source version this doesn't seem to be the case. An example response is below:

```{"meta"=>{"requestId"=>"97d16ba9-ea85-4d58-9257-d64fd0e739a5", "stringToSign"=>"GET\n2017-05-22T14:57:00Z+00:00\n/api/v1beta0/user/1/farms/112\n\n"}, "data"=>{"id"=>112, "name"=>"ScalrApiTestFarm", "description"=>"", "owner"=>{"id"=>2}, "project"=>{"id"=>"30c59dba-fc9b-4d0f-83ec-ffffffffffff"}, "timezone"=>"UTC", "launchOrder"=>"simulatenous"}, "warnings"=>[]}```

The documentation in this repository seems to match that response: https://github.com/Scalr/scalr/blob/master/api/doc/autodoc/definitions/Farm.mkd

Is the scalr api v2 explorer based upon the licensed version?

**Comment by recipe** [comment]
@davemeekin https://api-explorer.scalr.com/ related to the latest stable release of Enterprise Scalr.
