### ISSUE TITLE
Is Scalr real FOSS software?

### ISSUE THREAD

**Issue by fossxplorer** [Scalr/scalr#91]
I came across Scalr and read "Scalr is an open-source Cloud Management Platform (CMP)" with excitement to give it a try in a lab in the near future. I usually don't invest time learning non-FOSS software at all!  
After reading https://github.com/Scalr/scalr/issues/88, i see that the github repo doesn't contain any commit since 26.09.2016 with version 5.11 while Enterprise version is already on 7.6.1. It's pretty disappointing and i'd be worried to even invest time into this as i fail to see how such can be called true open source software? Where is the source code for newer versions thatn 5.11?

**Comment by SebastianStadil** [comment]
Thanks for dropping us a note. 5.11 indeed is the latest community release, and while we don't have an ETA for the next one, this one works great.

Let us know how things go in your lab!

**Comment by mrother** [comment]
Quick answer: NO. 
They grow on the shoulders of open source, and distance itself from the community when they are stablished in the market. It's really a shame.
